# Generated by Django 4.2.8 on 2023-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gameCreation', models.BigIntegerField()),
                ('gameDuration', models.BigIntegerField()),
                ('gameEndTimestamp', models.BigIntegerField(null=True)),
                ('gameId', models.BigIntegerField()),
                ('gameMode', models.CharField(max_length=255)),
                ('gameName', models.CharField(max_length=255)),
                ('gameStartTimestamp', models.BigIntegerField()),
                ('gameType', models.CharField(max_length=255)),
                ('gameVersion', models.CharField(max_length=255)),
                ('mapId', models.IntegerField()),
                ('platformId', models.CharField(max_length=255)),
                ('queueId', models.IntegerField()),
                ('tournamentCode', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
